name: Fly Deploy
on:
  push:
    branches: [ ma ]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_KEY }}
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      environment: 
        name: production
        url: https://cinotify.cc
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
